name: xayn_swipe_it_example
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  xayn_swipe_it:
    path: ../
  http: 0.13.4
  shared_preferences: 2.0.8
  share: 2.0.4
  url_launcher: 6.0.12
  cupertino_icons: 1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/
