name: xayn_swipe_it
description: A performant, animated swipe widget with customizable options on left and right provided by Xayn.
version: 0.0.1
homepage: https://github.com/xaynetwork
repository: https://github.com/xaynetwork/xayn_swipe_it
issue_tracker: https://github.com/xaynetwork/xayn_swipe_it/issues

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: 1.0.4
