name: Post merge checks

env:
  FLUTTER_VERSION: "2.5.2"

on:
  push:
    branches:
      - main

jobs:
  Basic-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: britannio/action-install-flutter@v1
        with:
          version: $FLUTTER_VERSION

      - name: Get Packages
        run: |
          flutter pub get

      - name: Flutter format
        run: |
          flutter format ./ --set-exit-if-changed

      - name: Flutter Analyze
        run: |
          flutter analyze lib test

      - name: Run Tests
        run: |
          flutter test --coverage

      - name: Upload coverage to codecov
        run: curl -s https://codecov.io/bash -t faf027c6-16e8-4b2d-b3a4-d240284fcfe9
        shell: bash
